version: '3.5'

services:
  ple-id-core:
    image: hyperledger/iroha:master
    container_name: ple-id-core
    depends_on:
      - ple-postgres
    restart: always
    tty: true
    environment:
      - KEY=keys/node0
      - IROHA_POSTGRES_HOST=localhost
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=postgres
      - IROHA_POSTGRES_PASSWORD=mysecretpassword
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    network_mode: host
    volumes:
      - ./iroha:/opt/iroha_data
    ports:
      - 50051:50051
      - 10001:10001
    logging:
       driver: none

  ple-postgres:
    image: postgres:9.5
    container_name: ple-postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    network_mode: host
    ports:
     - 5432:5432
    logging:
      driver: none
  
  ple-id-grpcwebproxy:
    build:
      context: grpcwebproxy/
    container_name: ple-id-grpcwebproxy
    depends_on:
      - ple-id-core
    entrypoint:
      - grpcwebproxy
      - --backend_addr=localhost:50051
      - --run_tls_server=false
      - --allow_all_origins=true
    network_mode: host
    logging:
      driver: none
    ports:
      - 8081:8080